# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Sep 30 12:35:06 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1110, 545)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralWidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 40, 681, 441))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 679, 439))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.match_table = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        self.match_table.setGeometry(QtCore.QRect(0, 0, 671, 431))
        self.match_table.setLineWidth(1)
        self.match_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.match_table.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.match_table.setAlternatingRowColors(False)
        self.match_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.match_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.match_table.setShowGrid(True)
        self.match_table.setRowCount(10)
        self.match_table.setColumnCount(2)
        self.match_table.setObjectName(_fromUtf8("match_table"))
        item = QtGui.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.match_table.setHorizontalHeaderItem(1, item)
        self.match_table.horizontalHeader().setVisible(True)
        self.match_table.horizontalHeader().setDefaultSectionSize(309)
        self.match_table.verticalHeader().setDefaultSectionSize(30)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.ok_button = QtGui.QPushButton(self.centralWidget)
        self.ok_button.setGeometry(QtCore.QRect(910, 450, 115, 32))
        self.ok_button.setObjectName(_fromUtf8("ok_button"))
        self.selecttop_rb = QtGui.QRadioButton(self.centralWidget)
        self.selecttop_rb.setGeometry(QtCore.QRect(740, 40, 204, 20))
        self.selecttop_rb.setChecked(True)
        self.selecttop_rb.setObjectName(_fromUtf8("selecttop_rb"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.selecttop_rb)
        self.createnew_rb = QtGui.QRadioButton(self.centralWidget)
        self.createnew_rb.setGeometry(QtCore.QRect(740, 330, 164, 20))
        self.createnew_rb.setObjectName(_fromUtf8("createnew_rb"))
        self.buttonGroup.addButton(self.createnew_rb)
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(770, 360, 251, 21))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.tophit_list = QtGui.QListWidget(self.centralWidget)
        self.tophit_list.setGeometry(QtCore.QRect(760, 70, 256, 241))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tophit_list.setFont(font)
        self.tophit_list.setObjectName(_fromUtf8("tophit_list"))
        self.delete_rb = QtGui.QRadioButton(self.centralWidget)
        self.delete_rb.setGeometry(QtCore.QRect(740, 410, 170, 20))
        self.delete_rb.setObjectName(_fromUtf8("delete_rb"))
        self.buttonGroup.addButton(self.delete_rb)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1110, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuRun = QtGui.QMenu(self.menuBar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionImport_auth = QtGui.QAction(MainWindow)
        self.actionImport_auth.setObjectName(_fromUtf8("actionImport_auth"))
        self.actionExport_CSV = QtGui.QAction(MainWindow)
        self.actionExport_CSV.setObjectName(_fromUtf8("actionExport_CSV"))
        self.actionSave_Project = QtGui.QAction(MainWindow)
        self.actionSave_Project.setEnabled(False)
        self.actionSave_Project.setObjectName(_fromUtf8("actionSave_Project"))
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setEnabled(False)
        self.actionOpen_Project.setObjectName(_fromUtf8("actionOpen_Project"))
        self.actionClose_Project = QtGui.QAction(MainWindow)
        self.actionClose_Project.setObjectName(_fromUtf8("actionClose_Project"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setEnabled(False)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionImport_messy = QtGui.QAction(MainWindow)
        self.actionImport_messy.setObjectName(_fromUtf8("actionImport_messy"))
        self.actionRun_matching = QtGui.QAction(MainWindow)
        self.actionRun_matching.setEnabled(False)
        self.actionRun_matching.setObjectName(_fromUtf8("actionRun_matching"))
        self.menuFile.addAction(self.actionImport_auth)
        self.menuFile.addAction(self.actionImport_messy)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.actionSave_Project)
        self.menuFile.addAction(self.actionClose_Project)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_CSV)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRun.addAction(self.actionRun_matching)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuRun.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        item = self.match_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nonstandard term", None))
        item = self.match_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Authority term", None))
        self.ok_button.setText(_translate("MainWindow", "Ok", None))
        self.selecttop_rb.setText(_translate("MainWindow", "Select authority from top hits", None))
        self.createnew_rb.setText(_translate("MainWindow", "Create a new authority", None))
        self.delete_rb.setText(_translate("MainWindow", "Delete current authority", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.actionImport_auth.setText(_translate("MainWindow", "Import Authorities...", None))
        self.actionExport_CSV.setText(_translate("MainWindow", "Export CSV...", None))
        self.actionSave_Project.setText(_translate("MainWindow", "Save Project...", None))
        self.actionOpen_Project.setText(_translate("MainWindow", "Open Project...", None))
        self.actionClose_Project.setText(_translate("MainWindow", "Close Project", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences...", None))
        self.actionImport_messy.setText(_translate("MainWindow", "Import Nonstandard Terms...", None))
        self.actionRun_matching.setText(_translate("MainWindow", "Match...", None))

